# Generated by Django 3.2.13 on 2022-05-31 18:35

import checkout.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_done_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_done_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Norway', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('DELIVERY', 'Delivery'), ('PICKUP', 'Pickup')], default=checkout.models.OrderType['PICKUP'], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
