# Generated by Django 3.2.13 on 2022-05-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220531_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_done_time',
            field=models.TimeField(null=True),
        ),
    ]
